      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Capacitor Update
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init Lumina com.lumina.app --web-dir dist
          npx cap add android
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Mashwara hai ke filhal 17 use karein stability ke liye
          cache: 'gradle' # Yeh line error khatam karne mein madad karegi

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
